#!/usr/bin/env python3
"""Auto-generate Makefile targets from every script in scripts/."""

from pathlib import Path

HEADER = """# Auto-generated by auto_makefile.py — do not edit manually
.PHONY: all help audit clean
"""

def generate() -> None:
    lines = [HEADER, "all: help\\n", "help:\\n\\t@echo 'Available targets:'\\n"]
    for py in sorted(Path("scripts").glob("*.py")):
        name = py.stem.replace("_", "-")
        lines.append(f"{name}:\\n\\t@python {py}\\n")
        lines.append(f"\\t@echo '  {name:<25} → {py.stem}'\\n")
    lines.append("\\nclean:\\n\\t@find . -type d -name '__pycache__' -exec rm -rf {} + 2>/dev/null; echo 'Cleaned caches'\\n")
    lines.append("\\naudit:\\n\\t@python scripts/workspace_audit.py\\n")
    Path("Makefile").write_text("".join(lines))
    print("✅ Makefile regenerated from scripts/")

if __name__ == "__main__":
    generate()
